name: wedweb
description: "Mobile app for wedwebs.com"
publish_to: 'none'
version: 0.2.3

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  uuid: ^4.4.2
  logging: ^1.2.0
  provider: ^6.1.2
  blue_thermal_printer: ^1.2.3
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  intl_phone_field: ^3.2.0
  excel: ^4.0.6
  qr_flutter: ^4.1.0
  file_picker: ^8.1.2
  flutter_easyloading: ^3.0.5
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  qr_code_scanner: ^1.0.1
  http: ^1.2.2
  connectivity_plus: ^6.0.5
  sqflite: ^2.3.3+1
  esc_pos_utils: ^1.1.0
  crypto: ^3.0.5
  statistics: ^1.1.2
  fl_chart: ^0.69.0
  dropdown_search: ^5.0.6
  url_launcher: ^6.3.0
  device_info_plus: ^10.1.2
  crypt: ^4.3.1
  flutter_contacts: ^1.1.9+2
  font_awesome_flutter: ^10.3.0
  event_bus: ^2.0.1
  esc_pos_bluetooth: ^0.4.1
  names_launcher: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.10.0"
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo-app.png"
  adaptive_icon_background: "#1F1D15"

names_launcher:
  name: "Wedwebs"
  platforms:
    android:
      enable: true
    ios:
      enable: true


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
